name: Fetch APIs and Log Data

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:      # Allows manual trigger

jobs:
  fetch-and-log:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install axios fs-extra

      - name: Fetch APIs and Save Data
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
        run: node fetchApis.js

      - name: Debug Remote URL
        run: |
          git remote -v  # Show the remote URL
          echo "Testing PAT access..."
          curl -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" https://api.github.com/user  # Test PAT

      - name: Commit and Push Changes
        env:
          GITHUB_PAT: ${{ secrets.PAT_TOKEN }}  # Use PAT for pushing changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          
          # Use PAT to set the URL
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}
          
          git add data/*.json
          git diff --cached --quiet || git commit -m "Updated API logs [$(date)]"
          git push || echo "No changes to push"
